name: Run test suite
on: push

jobs:
  run-tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        #- ${{ github.workspace }}:/app
         - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running composer install
        run: composer install
      - name: Running phpunit
        run: ./vendor/bin/phpunit tests
        
